services:
    database:
        image: mariadb
        container_name: portefolliocours
        environment:
            MARIADB_ROOT_PASSWORD: dev
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
